Fix displaying of MOSS sources
mrlvsb/kelvin pull request #306
Opened 2023-04-03 11:35 UTC by Kobzol

Before, MOSS result matches were automatically filtered and the match list was indexed by match ID. However, if some entries were filtered (which happened almost all the time), indexing by ID would yield incorrect results. Now matches are looked-up using their ID instead of using it directly as a list index.

Additionally, MOSS results can now be displayed for results that do not pass through the currently active filter. Adding the flag is dirty, but the `MossResult` API would need to be refactored completely to solve this easily in a different way.

2023-04-03 17:13 UTC, geordi commented
Will look at it tomorrow.

2023-04-04 09:22 UTC, geordi commented on web/views/moss.py
> +        matches = enrich_matches(rse.matches, request.user, task)
Looks like a typo. Should be `res`.

2023-04-04 09:32 UTC, geordi requested changes
Just fix the typo.

2023-04-04 09:34 UTC, geordi commented
At this point, somehow I don't see matches in the table but I see them in the graph. But this behavior I experience on running system without this PR.

2023-04-04 10:28 UTC, Kobzol commented on web/views/moss.py
> +        matches = enrich_matches(rse.matches, request.user, task)
Thanks!

2023-04-04 17:49 UTC, merged